# Generated by Django 5.2.6 on 2025-09-27 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Original text submitted by user')),
                ('improved_text', models.TextField(help_text='Text after improvements')),
                ('tools_used', models.JSONField(default=list, help_text='List of tools applied')),
                ('improvements_details', models.JSONField(default=dict, help_text='Detailed improvement information')),
                ('analysis_results', models.JSONField(default=dict, help_text='Analysis results from each tool')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Improvement',
                'verbose_name_plural': 'Text Improvements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_improvement_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Tool Usage Statistics',
                'verbose_name_plural': 'Tool Usage Statistics',
                'unique_together': {('tool_name',)},
            },
        ),
    ]
